### ISSUE TITLE
Google API only

### ISSUE THREAD

**Issue by SmooKboi** [widavies/VocalCord#1]
For the Speech Recegnition, can you choose between the Google API and Sphinx or do you have to have both?
Also, much thanks for the project!

**Comment by widavies** [comment]
Sorry didn't see this until now, I could hook up speech recognition to Sphinx, but it was really inaccurate through my testing, which is why I use Google API for more accurate translations. I am looking for a better speech recognition alternative that's free however, and will get back to you when (if) I find such.

**Comment by widavies** [comment]
Did a bit more research into this, apparently the speech models need to be trained for CMU Sphinx. Are you interested in helping with this @SmooKboi
